definitions:
  ApiResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: invalid request
        type: string
      type:
        example: validation_error
        type: string
    type: object
  Order:
    properties:
      couponCode:
        example: SAVE1000
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      items:
        items:
          $ref: '#/definitions/OrderItem'
        type: array
      products:
        items:
          $ref: '#/definitions/Product'
        type: array
    type: object
  OrderItem:
    properties:
      productId:
        example: "1"
        type: string
      quantity:
        example: 2
        type: integer
    type: object
  OrderItemReq:
    properties:
      productId:
        example: "1"
        type: string
      quantity:
        example: 2
        minimum: 1
        type: integer
    required:
    - productId
    - quantity
    type: object
  OrderReq:
    properties:
      couponCode:
        example: HAPPYHRS
        type: string
      items:
        items:
          $ref: '#/definitions/OrderItemReq'
        minItems: 1
        type: array
    required:
    - items
    type: object
  Product:
    properties:
      category:
        example: Pizza
        type: string
      id:
        example: "1"
        type: string
      name:
        example: Margherita Pizza
        type: string
      price:
        example: 12.99
        type: number
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health-check
  /order:
    post:
      consumes:
      - application/json
      description: Create a new order with items and optional coupon code
      parameters:
      - description: Order details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/OrderReq'
      - description: api_key must be set for authentication
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
      - ApiKeyAuth: []
      summary: Place a new order
      tags:
      - orders
  /product:
    get:
      description: Retrieve a list of all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Product'
            type: array
      summary: Get all products
      tags:
      - products
  /product/{productId}:
    get:
      description: Retrieve a single product by its ID
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiResponse'
      summary: Get product by ID
      tags:
      - products
swagger: "2.0"
